/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 Colors
        'background': '#121414',
        'surface': '#121414',
        'surface-dim': '#121414',
        'surface-bright': '#37393a',
        'surface-container-lowest': '#0c0f0f',
        'surface-container-low': '#1a1c1c',
        'surface-container': '#1e2020',
        'surface-container-high': '#282a2b',
        'surface-container-highest': '#333535',
        'on-background': '#e2e2e2',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#c4c7c7',
        'secondary': '#ffffff',
        'secondary-fixed': '#c3f400',
        'secondary-container': '#c3f400',
        'on-secondary': '#283500',
        'on-secondary-fixed': '#161e00',
        'on-secondary-fixed-variant': '#3c4d00',
        'on-secondary-container': '#556d00',
        'secondary-fixed-dim': '#abd600',
        'primary': '#c9c6c5',
        'primary-fixed': '#e5e2e1',
        'primary-fixed-dim': '#c9c6c5',
        'on-primary': '#313030',
        'on-primary-fixed': '#1c1b1b',
        'on-primary-container': '#797777',
        'on-primary-fixed-variant': '#474646',
        'tertiary': '#c8c6c5',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
        'tertiary-container': '#050505',
        'on-tertiary': '#313030',
        'on-tertiary-fixed': '#1c1b1b',
        'on-tertiary-fixed-variant': '#474746',
        'on-tertiary-container': '#787777',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'outline': '#8e9192',
        'outline-variant': '#444748',
        'inverse-surface': '#e2e2e2',
        'inverse-on-surface': '#2f3131',
        'inverse-primary': '#5f5e5e',
        'surface-tint': '#c9c6c5',
        'surface-variant': '#333535',
        // Legacy neon colors
        'neon-pink': '#ff0055',
        'neon-cyan': '#00f0ff',
        'neon-gold': '#ffb700',
        'neon-green': '#ccff00',
        'deep-black': '#050605',
        'card-black': '#0d0d11',
      },
      fontFamily: {
        'graffiti-clean': ['Sedgwick Ave Display', 'cursive'],
        'graffiti-raw': ['Permanent Marker', 'cursive'],
        'clean': ['Space Grotesk', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'button-text': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'button-text': ['14px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '800' }],
        'headline-xl': ['80px', { lineHeight: '72px', letterSpacing: '-0.05em', fontWeight: '900' }],
        'headline-lg': ['48px', { lineHeight: '48px', letterSpacing: '-0.04em', fontWeight: '900' }],
        'headline-md': ['24px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '32px', letterSpacing: '0em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
